### ISSUE TITLE
需要加强C#语言支持

### ISSUE THREAD

**Issue by sdcb** [THUDM/CodeGeeX2#1]
CodeGeeX2没有描述对C#语言的提升程度，只描述了对C++、Python、Java、JavaScript、Go、Rust有许多加强，希望能同时加入对C#语言的能力描述。

**Comment by Stanislas0** [comment]
您好，C#还没有相关的测试集，之后会考虑补充。CodeGeeX2的C#同样也是有提升的，可以尝试一下插件中C#的效果。

**Comment by sdcb** [comment]
![image](https://github.com/THUDM/CodeGeeX2/assets/1317141/deae0e8d-8f92-446c-84db-b0acc3159a02)
亲测了，目前C#的状态比较堪忧，希望在下一个版本中加强，C#开发者还是很庞大的。

**Comment by sdcb** [comment]
另一个示例，请他写个hello world，更加离谱：
![image](https://github.com/THUDM/CodeGeeX2/assets/1317141/bbed58d2-d0ed-45bb-9b1c-e5cf6a1f3f97)

**Comment by sdcb** [comment]
![image](https://github.com/THUDM/CodeGeeX2/assets/1317141/256f1d8c-905e-4c2b-b0fe-15d880a4cf8e)
看来主要应该是对python支持得比较好

**Comment by sdcb** [comment]
![image](https://github.com/THUDM/CodeGeeX2/assets/1317141/ed4445c1-b0ff-41a9-8775-9f572e680176)

**Comment by Stanislas0** [comment]
@sdcb Hi，你跑的结果是有问题的。开源的 CodeGeeX2-6B 是一个基座代码模型，它的使用方式是偏补全的，要按照某种语言的编程习惯来使用。比如C#应该使用“//”的注释符号，语言标签应该是`// language: C#`，prompt是`// [prompt]`。你的例子中使用了“#”，这是Python特有的注释符号，自然就生成了Python代码。正确的使用方式是像以下这个例子（[运行代码] (https://github.com/THUDM/CodeGeeX2/blob/main/demo/run_demo.py)）：

<img width="1418" alt="CleanShot 2023-07-26 at 21 43 09@2x" src="https://github.com/THUDM/CodeGeeX2/assets/26864197/e18d916b-c395-4c5c-8423-9cd7b1d51d85">

当然也可以直接尝试CodeGeeX插件中的对话功能，是经过指令微调的，生成结果更加准确：

<img width="686" alt="CleanShot 2023-07-26 at 21 44 23@2x" src="https://github.com/THUDM/CodeGeeX2/assets/26864197/8df460ca-c8b1-4352-9b93-d68bee75b320">

**Comment by sdcb** [comment]
感谢指出，那我应该找机会再去测测！

**Comment by lonngxiang** [comment]
> @sdcb Hi，你跑的结果是有问题的。开源的 CodeGeeX2-6B 是一个基座代码模型，它的使用方式是偏补全的，要按照某种语言的编程习惯来使用。比如C#应该使用“//”的注释符号，语言标签应该是`// language: C#`，prompt是`// [prompt]`。你的例子中使用了“#”，这是Python特有的注释符号，自然就生成了Python代码。正确的使用方式是像以下这个例子（[运行代码] ([https://github.com/THUDM/CodeGeeX2/blob/main/demo/run_demo.py)）：](https://github.com/THUDM/CodeGeeX2/blob/main/demo/run_demo.py)%EF%BC%89%EF%BC%9A)
> 
> <img alt="CleanShot 2023-07-26 at 21 43 09@2x" width="1418" src="https://user-images.githubusercontent.com/26864197/256250553-e18d916b-c395-4c5c-8423-9cd7b1d51d85.png">
> 当然也可以直接尝试CodeGeeX插件中的对话功能，是经过指令微调的，生成结果更加准确：
> 
> <img alt="CleanShot 2023-07-26 at 21 44 23@2x" width="686" src="https://user-images.githubusercontent.com/26864197/256250880-8df460ca-c8b1-4352-9b93-d68bee75b320.png">
为啥按格式输入，无结果输出呢
![image](https://github.com/THUDM/CodeGeeX2/assets/40717349/f3c539ab-48d7-479f-84a0-1f19abbb57cf)
