### ISSUE TITLE
VSCode 不断弹出提示框 Please open a file first to use CodeGeeX.

### ISSUE THREAD

**Issue by flingyp** [THUDM/CodeGeeX2#109]
我遇到这种情况：

当我没有打开任何文件的时候，我正在输入 commit message 内容的时候，右下角的会不断弹出提示框

![image](https://github.com/THUDM/CodeGeeX2/assets/57666140/3c719dac-73e9-419c-81c0-e828128a6eca)

**Comment by crazygo** [comment]
@flingyp 感谢你的反馈，我们已经在新版本中去掉了这个提示。

**Comment by flingyp** [comment]
@crazygo 是的，已经不会出现这个问题了。
