### ISSUE TITLE
how to insert only selected genereated codes from ask CodeGeex

### ISSUE THREAD

**Issue by Binman** [THUDM/CodeGeeX2#134]
Hi CodeGeeX
Thank you so much for developing such nice vscode extension!

One problem I encountered is that copy&paste (ctrl+c and ctrl+v) functions were disabled when ask codegeex is running.

That will be great if i could select certain generated code lines and directly insert into my scripts instead of the whole generated codes.

Thank you again!

Best,
Binman

**Comment by crazygo** [comment]
Thank you for your feedback, I need some time to validate this operation, I will reply later. @Binman

**Comment by crazygo** [comment]
Hi @Binman ,
Are you wanting to copy and paste a few lines from the code block into ipynb?

We found that there indeed is a problem with copying and pasting directly between vscode and ipynb. This seems to be an issue related to the notebook extension, we are still investigating how to resolve it.
