### ISSUE TITLE
最新版本的插件在vscode中和系统自己的代码提示冲突了，有什么解决的方案吗

### ISSUE THREAD

**Issue by Whbbit1999** [THUDM/CodeGeeX2#194]
最新版本的插件在vscode中和系统自己的代码提示冲突了，我试着改了下快捷键，发现任然无法解决。请问大家有遇到同样的问题吗？有什么解决的方案吗

**Comment by crazygo** [comment]
你好，请问是哪个快捷键有冲突？用的是什么操作系统？

**Comment by Whbbit1999** [comment]
command + i 和vscode原有的代码提示冲突了

**Comment by crazygo** [comment]
感谢两位反馈问题。通过这种方式可以设置冲突的快捷键
1、打开快捷键设置窗口（使用command+shift+p，搜索keyboard shortcuts）
2、搜索需要修改的快捷键，如command+i
![image](https://github.com/THUDM/CodeGeeX2/assets/9395888/1e7662c0-1ab8-46ba-817c-43a297392df6)
3、找到`open cat`项目，可以指定新的快捷键，或者用 command+ backspace 删除快捷键。

**Comment by Whbbit1999** [comment]
可以了，谢谢您
