### ISSUE TITLE
[BUG] CodeGeeX提示和代码补全冲突

### ISSUE THREAD

**Issue by SoTosorrow** [THUDM/CodeGeeX2#199]
**开发环境：**
win11、vscode1.85.2、插件CodeGeeX最新版（截止至2024-1-22）、clangd

**问题描述：**
写代码过程中，代码补全和AI提示都出现时，按tab使用了AI提示的代码，但是“待补全选择框”不会关闭，且换行等操作都不能进行。

tab选择前
![image](https://github.com/THUDM/CodeGeeX2/assets/50233205/3084e324-92f2-434b-95c8-b6ccf4bfd7b6)

tab选择后
![image](https://github.com/THUDM/CodeGeeX2/assets/50233205/e5719896-4102-40e7-9fbd-8305d9bf760d)

此刻回车、空格，都无法操作，只能关闭文件，或者偶尔幸运的通过删减关掉了提示框。

**问题解释：**
猜测是AI提示优先级可能大于代码补全、使补全后待选框失去焦点之类的目标无法关闭，阻塞了编辑器的正常运行。

**Comment by crazygo** [comment]
感谢 SoTosorrow 反馈问题。我使用 vscode 做了测试，并没有复现你描述的问题（tab会会关闭vscode给的备选项）。可能还有和你的环境不一致的地方，方便的话请加我的微信 `nob301` ，和研发同学一起排查一下。

**Comment by SoTosorrow** [comment]
> 感谢 SoTosorrow 反馈问题。我使用 vscode 做了测试，并没有复现你描述的问题（tab会会关闭vscode给的备选项）。可能还有和你的环境不一致的地方，方便的话请加我的微信 `nob301` ，和研发同学一起排查一下。

晚一些我用朋友的环境试试吧，如果还有问题再联系您

**Comment by SoTosorrow** [comment]
> 感谢 SoTosorrow 反馈问题。我使用 vscode 做了测试，并没有复现你描述的问题（tab会会关闭vscode给的备选项）。可能还有和你的环境不一致的地方，方便的话请加我的微信 `nob301` ，和研发同学一起排查一下。

我自己的两台电脑都有这个问题，朋友的电脑也复现不出来，可能是我自定义配置什么导致的吧，既然无法复现，那我就关闭issue了，感谢您对问题的关注。也感谢codegeex和chatglm的工作，对我帮助很大 :)

**Comment by crazygo** [comment]
感谢你的反馈 😄
