### ISSUE TITLE
1

### ISSUE THREAD

**Issue by whitesay** [THUDM/CodeGeeX2#23]

**Comment by q497629642** [comment]
我自己看他们的源代码有个stream_generate函数，codegeex官方的人好像很忙，没时间回答[破涕为笑]

```
inputs = tokenizer.encode(prompt, return_tensors="pt").to(model.device)
n_token_prompt = len(inputs[0])
for tokens in model.stream_generate(inputs, max_new_tokens=out_seq_length, top_k=self.config.topk):
          response = self.tokenizer.decode(tokens[0][n_token_prompt:])
```

**Comment by whitesay** [comment]
哇！好嘞！感谢感谢！






------------------ 原始邮件 ------------------
发件人: q497629642 ***@***.***&gt;
发送时间: 2023年7月28日 17:31
收件人: THUDM/CodeGeeX2 ***@***.***&gt;
抄送: whitesay ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THUDM/CodeGeeX2] 请问一下支持流式输出吗？谢谢 (Issue #23)





 
我自己看他们的源代码有个stream_generate函数，codegeex官方的人好像很忙，没时间回答[破涕为笑]
 inputs = tokenizer.encode(prompt, return_tensors="pt").to(model.device) n_token_prompt = len(inputs[0]) for tokens in model.stream_generate(inputs, max_new_tokens=out_seq_length, top_k=self.config.topk):           response = self.tokenizer.decode(tokens[0][n_token_prompt:])
