### ISSUE TITLE
vscode插件的界面字体能不能优化一下

### ISSUE THREAD

**Issue by freeorca** [THUDM/CodeGeeX2#256]
![图片](https://github.com/THUDM/CodeGeeX2/assets/36132130/3df2e253-1d80-492c-b79c-f9c8a0b50c47)
开发组全是mac和linux，没有用中文windows的吗？win版的代码的这个宋体英文简直没法看啊。
本插件目录/webview-ui/dist/assets 下的index.css这个文件里写着
```
code.hljs {
  padding: 3px 5px;
  font-size: var(--code-editor-font-size);
  font-family: var(--code-editor-font-family);
}
```
这一段控制代码字体，结果这font-family指定的--code-editor-font-family这个变量，在本css文件里根本就没有定义。运行起来鬼知道会fallback到哪个字体去，我这里直接就到宋体了。自己在文件开头加一行定义
`--code-editor-font-family: var(--vscode-editor-font-family);`
观感就能好很多。
<br>
<br>
![图片](https://github.com/THUDM/CodeGeeX2/assets/36132130/00077846-f24a-49ef-b0f3-6369c1942028)
然后图里“items()”、“keys()”、“values()”这一类的字体都受这个
```
code,
kbd,
samp {
  font-family: monospace, monospace;
  font-size: 1em;
}
```
这一段控制。就这么一个宽泛的monospace，简体中文windows很容易又找到宋体去了。
我自己用也不需要考虑多平台兼容性，反正就把code单独提出来硬改了下字体，观感就好一些。
![图片](https://github.com/THUDM/CodeGeeX2/assets/36132130/22561a51-8ed7-4fdd-8433-610eeb499319)
<br>
<br>
虽然自己改能好看点，但每次插件更新后都要重新改也挺烦的，希望开发组能优化下index.css，让字体顺眼点。
顺便说一下，插件在浅色主题下的代码配色也有点问题，键还显眼，值太不显眼。

**Comment by freeorca** [comment]
感谢新版修改了css文件，但修改后的文件还存在2处问题，导致设置无法生效。
<br>
1. 此处缺了一个分号，会导致设置不生效，需要自己添加。
![图片](https://github.com/THUDM/CodeGeeX2/assets/36132130/37a96eb8-6844-41fa-b47f-70cc4fbd99f7)

2. code.hljs里多了一行“--code-editor-font-family: var(--code-editor-font-family);”，会导致设置不生效，需要自己删掉或注释掉这一行。
![图片](https://github.com/THUDM/CodeGeeX2/assets/36132130/1fbd0a18-0b34-40fc-83ff-7d81b378d4d4)

**Comment by crazygo** [comment]
感谢反馈，我们处理一下

**Comment by freeorca** [comment]
新版显示没啥问题了，感谢开发组的积极改进😊
