### ISSUE TITLE
代码还是模型抽风了

### ISSUE THREAD

**Issue by bitores** [THUDM/CodeGeeX2#28]
![image](https://github.com/THUDM/CodeGeeX2/assets/17512181/3a4922d7-ab44-4f71-8905-b1e21159178a)
自问自答，输出不断

**Comment by bitores** [comment]
![image](https://github.com/THUDM/CodeGeeX2/assets/17512181/0c907cb6-91a8-4333-8340-9f7bc95aacce)

**Comment by Stanislas0** [comment]
> ![image](https://user-images.githubusercontent.com/17512181/256838738-3a4922d7-ab44-4f71-8905-b1e21159178a.png) 自问自答，输出不断

开源版本CodeGeeX2是一个基座代码生成模型，没有经过指令微调，不具备聊天功能。可以到插件中体验“Ask CodeGeeX”功能，提问和编程相关的问题。
