### ISSUE TITLE
[Unexpected token '<', "<html> <h"... is not valid JSON]启动run_demo.py运行时出现此报错

### ISSUE THREAD

**Issue by donjuanplatinum** [THUDM/CodeGeeX2#32]
```
Unexpected token '<', "<html> <h"... is not valid JSON
```
![QQ截图20230731011610](https://github.com/THUDM/CodeGeeX2/assets/113148619/de2c7c36-3a59-4e5d-8f8f-560331776b13)
![1](https://github.com/THUDM/CodeGeeX2/assets/113148619/26522576-0169-4199-b2a3-dbed891e64df)

环境|配置
---|---
错误信息|Unexpected token '<', "<html> <h"... is not valid JSON
推理设备|CPU
操作系统|linux
使用脚本|run_demo.py

**Comment by Stanislas0** [comment]
> ```
> Unexpected token '<', "<html> <h"... is not valid JSON
> ```
> 
> ![QQ截图20230731011610](https://user-images.githubusercontent.com/113148619/257065683-de2c7c36-3a59-4e5d-8f8f-560331776b13.png) ![1](https://user-images.githubusercontent.com/113148619/257065765-26522576-0169-4199-b2a3-dbed891e64df.png)
> 
> 环境	配置
> 错误信息	Unexpected token '<', " <h"... is not valid JSON
> 推理设备	CPU
> 操作系统	linux
> 使用脚本	run_demo.py

这个是gradio的bug，估计是网络问题丢包导致。重新点Generate可以再次生成。

**Comment by donjuanplatinum** [comment]
> 

不知道是不是因为反向代理的原因,因为默认只监听127.0.0.1.
我一直出现这个问题无法生成代码

**Comment by donjuanplatinum** [comment]
如何改成监听0.0.0.0呢,也许改成0.0.0.0会修复这个问题

**Comment by lileilai** [comment]
> 如何改成监听0.0.0.0呢,也许改成0.0.0.0会修复这个问题
改成监听0.0.0.0也还是无法生成代码，

**Comment by lileilai** [comment]
> 如何改成监听0.0.0.0呢,也许改成0.0.0.0会修复这个问题

改成监听0.0.0.0也还是无法生成代码，还是报“Unexpected token '<', " <h"... is not valid JSON”的错误

**Comment by donjuanplatinum** [comment]
> 

你试试最新提交的里面的改法,我改了后就好了

**Comment by fucking-dog** [comment]
想问一下这个最新提交里面是指demorun的嘛

**Comment by donjuanplatinum** [comment]
> 

已经合并了哦
