### ISSUE TITLE
RuntimeError: Unknown platform: darwin

### ISSUE THREAD

**Issue by YingchaoX** [THUDM/CodeGeeX2#55]
envs:
- Mac studio M2pro
- Python 3.11.4 

code
```python
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/codegeex2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/codegeex2-6b", trust_remote_code=True)
model = model.eval()

# remember adding a language tag for better performance
prompt = "# language: Python\n# write a bubble sort function\n"
inputs = tokenizer.encode(prompt, return_tensors="pt")
outputs = model.generate(inputs, max_length=256, top_k=1)
response = tokenizer.decode(outputs[0])
print(response)
```

error
```bash
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/__init__.py", line 1, in <module>
    from . import library
  File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/library/__init__.py", line 1, in <module>
    from . import nvrtc
  File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/library/nvrtc.py", line 5, in <module>
    nvrtc = Lib("nvrtc")
            ^^^^^^^^^^^^
  File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/library/base.py", line 59, in __init__
    raise RuntimeError("Unknown platform: %s" % sys.platform)
RuntimeError: Unknown platform: darwin
```

**Comment by donjuanplatinum** [comment]
您可以用CPU试试

**Comment by YingchaoX** [comment]
> > envs:
> > 
> > * Mac studio M2pro
> > * Python 3.11.4
> > 
> > code
> > ```python
> > from transformers import AutoTokenizer, AutoModel
> > tokenizer = AutoTokenizer.from_pretrained("THUDM/codegeex2-6b", trust_remote_code=True)
> > model = AutoModel.from_pretrained("THUDM/codegeex2-6b", trust_remote_code=True)
> > model = model.eval()
> > 
> > # remember adding a language tag for better performance
> > prompt = "# language: Python\n# write a bubble sort function\n"
> > inputs = tokenizer.encode(prompt, return_tensors="pt")
> > outputs = model.generate(inputs, max_length=256, top_k=1)
> > response = tokenizer.decode(outputs[0])
> > print(response)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error
> > ```shell
> >   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
> >     return _bootstrap._gcd_import(name[level:], package, level)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
> >   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
> >   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
> >   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> >   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> >   File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/__init__.py", line 1, in <module>
> >     from . import library
> >   File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/library/__init__.py", line 1, in <module>
> >     from . import nvrtc
> >   File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/library/nvrtc.py", line 5, in <module>
> >     nvrtc = Lib("nvrtc")
> >             ^^^^^^^^^^^^
> >   File "ChatGLM2-6B-main/venv/lib/python3.11/site-packages/cpm_kernels/library/base.py", line 59, in __init__
> >     raise RuntimeError("Unknown platform: %s" % sys.platform)
> > RuntimeError: Unknown platform: darwin
> > ```
> 
> You need to install the nightly version of Pytorch that supports darwin. Ref to: https://github.com/THUDM/CodeGeeX2/blob/main/docs/zh/inference_zh.md#mac%E6%8E%A8%E7%90%86

thx~
