### ISSUE TITLE
idea插件使用BUG

### ISSUE THREAD

**Issue by 2574021892** [THUDM/CodeGeeX2#56]
在一个项目时正常
在多个项目使用时回出现选中的代码出现在别的项目的codegeex对话框中的问题

场景
1.开启项目A，打开codegeek，选中代码，选中代码会出现在项目A对应的codegeex对话框中
2.开启项目B，打开codegeek，选中代码，选中代码会出现在项目B对应的codegeex对话框中
3.回到项目A，选中代码，选中代码，选中代码会出现在项目B对应的codegeex对话框中
4.回到项目B，选中代码，选中代码，选中代码会出现在项目B对应的codegeex对话框中
之后无论在哪里选中代码 选中的代码都会出现在后打开的项目中的对话框中，包括ask translation 等功能

**Comment by 2574021892** [comment]
补充 即使关闭项目B 项目A里仍然无法触发

**Comment by jues** [comment]
Hi, thanks for submitting the bug, could you please try version 1.1.6 for Jetbrains?

**Comment by 2574021892** [comment]
> Hi, thanks for submitting the bug, could you please try version 1.1.6 for Jetbrains?

1.1.6测试已解决此问题

**Comment by jues** [comment]
Thanks again for submitting the bug, I'll close this issue for now.
