### ISSUE TITLE
update requirements

### ISSUE THREAD

**Issue by kid9** [THUDM/CodeGeeX2#62]
Package gradio is required, pls updates the requirements.txt
run ./demo/run_demo.py, it throws error:

# pip install -r requirements.txt
# python3 run_demo.py  --port 8001 --listen 0.0.0.0

Traceback (most recent call last):
  File "/root/codegeex/CodeGeeX2/./demo/run_demo.py", line 7, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by Stanislas0** [comment]
Added. Thanks for reminding!
