### ISSUE TITLE
How to return completion only without the prompt ?

### ISSUE THREAD

**Issue by kid9** [THUDM/CodeGeeX2#69]
As the quick-start example shows, currently `model.generate` will return both prompt and completion, how to make it return completion only?
An example is as follows:

Prompt: 

```
# language: Python
# write a bubble sort function
```

Current Response:
```
# language: Python
# write a bubble sort function

def bubble_sort(list):
    for i in range(len(list) - 1):
        for j in range(len(list) - 1):
            if list[j] > list[j + 1]:
                list[j], list[j + 1] = list[j + 1], list[j]
    return list
```

Expected Response:
```
def bubble_sort(list):
    for i in range(len(list) - 1):
        for j in range(len(list) - 1):
            if list[j] > list[j + 1]:
                list[j], list[j + 1] = list[j + 1], list[j]
    return list
```

**Comment by Stanislas0** [comment]
> As the quick-start example shows, currently `model.generate` will return both prompt and completion, how to make it return completion only? An example is as follows:
> 
> Prompt:
> 
> ```
> # language: Python
> # write a bubble sort function
> ```
> 
> Current Response:
> 
> ```
> # language: Python
> # write a bubble sort function
> 
> def bubble_sort(list):
>     for i in range(len(list) - 1):
>         for j in range(len(list) - 1):
>             if list[j] > list[j + 1]:
>                 list[j], list[j + 1] = list[j + 1], list[j]
>     return list
> ```
> 
> Expected Response:
> 
> ```
> def bubble_sort(list):
>     for i in range(len(list) - 1):
>         for j in range(len(list) - 1):
>             if list[j] > list[j + 1]:
>                 list[j], list[j + 1] = list[j + 1], list[j]
>     return list
> ```

It's easy, you just need to add the following:
```
response = tokenizer.decode(outputs[0][inputs.shape[-1]:])
print(response)
```

**Comment by kid9** [comment]
> > As the quick-start example shows, currently `model.generate` will return both prompt and completion, how to make it return completion only? An example is as follows:
> > Prompt:
> > ```
> > # language: Python
> > # write a bubble sort function
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Current Response:
> > ```
> > # language: Python
> > # write a bubble sort function
> > 
> > def bubble_sort(list):
> >     for i in range(len(list) - 1):
> >         for j in range(len(list) - 1):
> >             if list[j] > list[j + 1]:
> >                 list[j], list[j + 1] = list[j + 1], list[j]
> >     return list
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Expected Response:
> > ```
> > def bubble_sort(list):
> >     for i in range(len(list) - 1):
> >         for j in range(len(list) - 1):
> >             if list[j] > list[j + 1]:
> >                 list[j], list[j + 1] = list[j + 1], list[j]
> >     return list
> > ```
> 
> It's easy, you just need to add the following:
> 
> ```
> response = tokenizer.decode(outputs[0][inputs.shape[-1]:])
> print(response)
> ```

Thx for answering. I had already used this method. I'm wondering if there are some configs or params to achieve this ?

**Comment by Stanislas0** [comment]
Please just modify the code in run_demo.py, then it will work fine.

**Comment by lonngxiang** [comment]
> Please just modify the code in run_demo.py, then it will work fine.

为什么我run run_demo.py,没有代码结果输出
![image](https://github.com/THUDM/CodeGeeX2/assets/40717349/66b5fa69-5777-46ec-91e8-0d0ea497fc20)
