### ISSUE TITLE
IDEA中生成的注释，如何显示为中文

### ISSUE THREAD

**Issue by Caozc** [THUDM/CodeGeeX2#75]
我看示例中都显示中文注释，但并未在IDEA中找到设置项

**Comment by javakam** [comment]
+1

**Comment by CeresY** [comment]
+1，每次还要自己翻译，头疼

**Comment by alephpi** [comment]
可以看看这儿 https://codegeex.cn/zh-CN/bloginfo/e26154d394974ad19991af258bd81740

**Comment by Caozc** [comment]
> 

谢谢

**Comment by EmptyKYP** [comment]
> 可以看看这儿 https://codegeex.cn/zh-CN/bloginfo/e26154d394974ad19991af258bd81740

我是goland2023.3.3,设置了生成注释为中文，但是没效果，还是输出得英文
